Support for vanilla animation tables
Fast-64/fast64 pull request #130
Opened 2022-08-15 20:58 UTC by Lilaa3

Added support for vanilla animation tables.

2022-08-21 13:52 UTC, thecozies requested changes
smol suggestion

2022-08-21 13:52 UTC, thecozies commented on fast64_internal/sm64/sm64_anim.py
> +		stringData = stringData[:footerIndex] + '\t&{0},\n'.format(sm64_anim.header.name) + stringData[footerIndex:]
we've mostly moved to using f-strings when possible

```suggestion
		stringData = stringData[:footerIndex] + f'\t&{sm64_anim.header.name},\n' + stringData[footerIndex:]
```

2022-09-25 19:42 UTC, Dragorn421 requested changes
I'm not a sm64 person so I can't tell as for what this achieves, just two comments on the python. Sorry for the delay

(and @thecozies bump?)

2022-09-25 19:42 UTC, Dragorn421 commented on fast64_internal/sm64/sm64_anim.py
> +	fileData.close()
```suggestion
	with open(tableFilePath, 'r') as f:
		stringData = f.read()
```
(if you want to read, see
https://docs.python.org/3/tutorial/inputoutput.html#tut-files
https://docs.python.org/3/reference/datamodel.html#context-managers )

2022-09-25 19:42 UTC, Dragorn421 commented on fast64_internal/sm64/sm64_anim.py
> +		fileData.close()
```suggestion
		with open(tableFilePath, 'w', newline = '\n') as f:
			f.write(stringData)
```

2022-09-27 12:48 UTC, Dragorn421 commented on fast64_internal/sm64/sm64_anim.py
> +	fileData.close()
you're a lot less late than we are on the review :sweat_smile: , and to me not late at all anyway, few days of delay is perfectly fine

2022-09-27 12:49 UTC, Dragorn421 approved these changes
code is okay to me, but I'm not a sm64 person

2022-09-27 13:31 UTC, thecozies approved these changes
# nice

2022-09-27 13:32 UTC, merged