Custom gSPSegment and improve sequence numbering
Fast-64/fast64 pull request #3
Opened 2021-07-30 04:24 UTC by sauraen

- Add 1 to sequence number in export so that in-game sequence number is as expected
- Add two optional custom gSPSegment addresses to material editor

2021-08-03 08:36 UTC, Dragorn421 requested changes
Sorry, didn't see the PRs until right now by accident. Didn't enable notifications for the repo

Ideally we would want to allow an arbitrary amount of such "custom" jumps but two is probably plenty enough, and a CollectionProperty needs more work

2021-08-03 08:36 UTC, Dragorn421 commented on fast64_internal/oot/oot_f3d_writer.py
> +		name = "Custom " + str(colIndex) + " " + suffix
```suggestion
		name = "Jump to (" + str(colIndex + 1) + ") " + suffix
```
I think "custom" is a pretty bad name to use for everything (way too generic), maybe change `custom` to `customJump`

2021-08-03 08:36 UTC, Dragorn421 commented on fast64_internal/oot/oot_f3d_writer.py
> +	custom0_seg : bpy.props.StringProperty()
```suggestion
	custom0_seg : bpy.props.StringProperty(description="Segment address of a display list to jump to")
```

2021-08-03 08:48 UTC, Dragorn421 commented
hijacking this pr to test the webhook

2021-08-03 17:34 UTC, Zelllll commented
Yep I agreed with Dragorn's suggestions, although eventually I'd like to simply remove all the check boxes too and just let users choose as many segments as they want instead, I think it would be worth breaking compatibility with existing stuff to make that change.

2021-08-03 20:47 UTC, Dragorn421 commented
First

2021-08-04 20:04 UTC, sauraen commented
I started working on changing over the segments to a collection, but I realized that the fast64 infrastructure for creating GUI for editing collections is based on the collection in question being some sub-property of an object. This collection would be a sub-property of a material, which means I'd have to make completely new GUI for this or make substantial changes to the existing infrastructure. Combined with the fact that this will break scenes (or the extra work of checking for both types of segment commands), I don't think it's worth it.

I've changed the names to "custom call". It's more like a function call than a jump, as execution returns to the current DL.

2021-08-04 20:06 UTC, Zelllll commented
Hm I was thinking using the same gui as the object list, just simply have an add button for a segment, and also allowing you to reorder them so they get called in the specific order you want

2021-08-04 20:09 UTC, sauraen commented
Right, so I tried that, and it does not work, because the GUI infrastructure for displaying the elements of a collection with the add/remove/up/down buttons etc. all depends on the collection you're editing being a sub-property of an object in the scene. This collection would be a sub-property of a material, not an object. So it is not compatible with that GUI infrastructure.

2021-08-05 07:13 UTC, Dragorn421 reviewed
I did expect `CollectionProperty` to be some work, but not because of fast64, as I said before it will be fine as is, two custom calls is plenty enough.

2021-08-05 07:13 UTC, Dragorn421 commented on fast64_internal/oot/oot_f3d_writer.py
> +	customCall1_seg : bpy.props.StringProperty()
```suggestion
	customCall0_seg : bpy.props.StringProperty(description="Segment address of a display list to call")
	customCall1 : bpy.props.BoolProperty()
	customCall1_seg : bpy.props.StringProperty(description="Segment address of a display list to call")
```
I plan to eventually add a description for every property to make it more user friendly, may as well start now.
Those are displayed in the tooltip when hovering over a property, imo it's a great way to document whatever a property is for

2021-08-06 04:49 UTC, sauraen commented
I've added the descriptions you requested.

2021-08-06 07:12 UTC, Dragorn421 approved these changes

2021-08-06 07:14 UTC, merged