[F3D] Fog Export Fix
Fast-64/fast64 pull request #350
Opened 2024-05-26 17:57 UTC by jesusyoshi54

Fog now exports only when the `set_fog` boolean is checked and fog is used in the material, which is determined if `g_fog` is enabled, or if fog is an input to any of the blend variables. Previous behavior only checked if `set_fog` was on, which would mistakenly allow fog to be exported when the `set_fog` checkbox was invisible (and left checked from prev config) if material was changed to no longer have any fog inputs.

2024-05-31 18:23 UTC, Lilaa3 commented
I don´t know if I like this, one could use the alpha in the combiner with a texedge render mode for example, and this would break that ability. Also I don't see the behavior you are describing of fog being hidden in the UI?

2024-05-31 19:41 UTC, jesusyoshi54 commented
> I don´t know if I like this, one could use the alpha in the combiner with a texedge render mode for example, and this would break that ability.

I'm not sure what will be broken here.

> Also I don't see the behavior you are describing of fog being hidden in the UI?
Then I must be dumb and mistaken. I could have sworn this was an issue, but it might have been fixed sometimes with the render mode changes sauraen made.

2024-05-31 20:20 UTC, Lilaa3 commented
What will be broken is that, since the material is technically not using fog in render mode, fast64 will just not export the actual fog

2024-05-31 22:48 UTC, jesusyoshi54 commented
If fog isn't used in the render mode then why would it matter if it is unset.
If you're using shade alpha in the combiner you need g_fog enabled, in which case it will export.

2024-06-01 00:29 UTC, Dragorn421 commented
Hm I'd like to point out the combiner may use shade alpha without intending for fog, with said alpha being provided by the user in the Vtx data (alongside either verter colors or normals)

2024-06-01 08:21 UTC, Lilaa3 commented
Ah sorry I misread this, I thought you were checking for both g_fog and a fog render mode, my bad, and also set fog does get hidden still, sorry for so much confusion on my part

2024-06-01 08:48 UTC, Lilaa3 requested changes
I really like the way you implemented these changes, Just a few small details

2024-06-01 08:48 UTC, Lilaa3 commented on fast64_internal/f3d/f3d_material.py
> +        return self.blend_alpha_inputs
Did you mean to do something like
```suggestion
        return self.blend_color_inputs + self.blend_alpha_inputs
```

2024-06-01 08:48 UTC, Lilaa3 commented on fast64_internal/f3d/f3d_material.py
> +        return self.g_fog or any(["FOG" in input for input in self.blend_inputs])
I personally would just check for the two blend modes directly for the sake of clarity, color inputs will never get new inputs added there is just those two for fog so its good to make that explicit I think
```suggestion
        return self.g_fog or self.does_blender_use_input("G_BL_CLR_FOG") or self.does_blender_use_input("G_BL_A_FOG")
```

2024-06-01 08:48 UTC, Lilaa3 commented on fast64_internal/f3d/f3d_material.py
> +        return False
this logic could be one line
```suggestion
        return any(input == setting for input in self.blend_inputs)
```

2024-06-07 22:02 UTC, jesusyoshi54 commented on fast64_internal/f3d/f3d_material.py
> +        return self.blend_alpha_inputs
These are generators so I did mean that

2024-06-08 08:25 UTC, Lilaa3 approved these changes
The code works perfectly, I like how it is written, merge soon.

2024-06-11 06:56 UTC, merged